#!/bin/bash

# Get JWT token (you'll paste yours)
echo "Paste your JWT token:"
read JWT_TOKEN

echo ""
echo "Creating test article with the generated image..."
echo ""

# MCP protocol call to create_content
curl -k -X POST https://localhost:5001/api/mcp \
  -H "Authorization: Bearer $JWT_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "tools/call",
    "params": {
      "name": "create_content",
      "arguments": {
        "author": "AI Test",
        "title": "Test Article: Chocolate Cake",
        "subtitle": "Generated with OpenAI DALL-E integration",
        "content": "# Amazing Chocolate Cake\n\nCheck out this delicious chocolate cake generated by AI:\n\n![Chocolate Cake](https://localhost:5001/api/images/1)\n\nThis image was automatically generated using OpenAI'\''s DALL-E API and saved to our CMS!",
        "imageIds": "1",
        "draft": true
      }
    }
  }'

echo ""
echo ""
echo "If successful, you can view the draft at http://localhost:4300/drafts"
